server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: admin-client

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always