
eureka:
  client:
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
server:
  port: 7001
spring:
  application:
    name: eureka-server
